### ISSUE TITLE
Duplicate User/Comments ID's when creating entries in Database and unnecessary ResumeID 

### ISSUE THREAD

**Issue by ynigoreyes** [ynigoreyes/resume-engine#14]
Gorm automatically gives us primary key ids. There are two ways we can go about this. We can un-inherit `gorm.Model` and handle PK and FK manually (my choice) so that it is easier for demos and injecting data into the app. Or we can delete `user_id` and `comment_id` and have gorm handle the joins.

**Comment by swoldemi** [comment]
I didn't realize `gorm.Model` provided  `ID`, `CreatedAt`, `UpdatedAt`, `DeletedAt`. Injecting data would be done by using MySQL workbench and doing a manual insertion or script call, no? I'll delete `User.UserID`, but I thought you said `Comment.CommenterID` would be a foreign key to associate who posted the comment? We could so something like http://doc.gorm.io/associations.html#belongs-to (third example)

**Comment by ynigoreyes** [comment]
ooooOOooOOOoo that's cool lol. Yes, we would be populating the database manually through MySQL Workbench so that they can see the actual SQL statement and how it connects to Cloud SQL. If we are going to keep `gorm.Model`, you **should** delete the `User.UserID` key and then just use gorm's id as the FK: `Comment.CommenterID`

Also, we don't need `*.ResumeID` since the comments are already related to the UserID. The **actual** resume object will not be linked to any user. It's just for show.

**Comment by swoldemi** [comment]
Got it! I'll make these changes soon 👌
