### ISSUE TITLE
Need to connect React to Cloud Storage

### ISSUE THREAD

**Issue by ynigoreyes** [ynigoreyes/resume-engine#2]
We need this to store resumes in here that are public so that we can see them from the browser.

I just realized that we are not going to be touching the API at all for this. We just need to figure out how to display the PDF to the user in a new tab

**Comment by swoldemi** [comment]
Should we setup CI for building the client and pushing it to the bucket using the `gsutil` cli?

**Comment by ynigoreyes** [comment]
No, I don't think that's necessary. Just build and deploy on your own. Only deploy if you are on master branch though.
